# Funding options for AstraPDF
# Uncomment and fill in your information when ready

# github: [your-github-username]
# patreon: your-patreon-username
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-buymeacoffee-username
# custom: ["https://astrapdf.com/sponsor", "https://astrapdf.com/donate"]
